### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by andywynkoop** [GhostOfColin/wavecloud1#1]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by andywynkoop** [comment]
Hey Colin, your site's looking great so far, here are a few (mostly styling) changes to make:
- [ ] The logo (image and words) are a little too large on the splash page
- [ ] Buttons for login/signup on splash should all be uniform in size, font, etc. and line up with each other
- [ ] All fonts should match Soundcloud as closely as possible - it looks like you're still using a default font in certain places
- [ ] I think the `Start Uploading Now` button should probably just link you to sign up or something
- [ ] The `Wavecloud` part of the logo should also be clickable and redirect to `/`
- [ ] It looks like Soundcloud uses modals for session forms, you should do the same
- [ ] It appears you have all of the basic functionality working, but you still need to style your session forms/ input/ errors/ etc. to match Soundcloud as closely as possible. Once you do that, I can check off this MVP

**Comment by GhostOfColin** [comment]
Hey Andy, I think these are done.  Let me know what you think!
